### ISSUE TITLE
Add Procambarus virginalis

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-natagora-checklist#2]
Origineel hier gerapporteerd: https://github.com/inbo/alien-species-portal/issues/57#issuecomment-1798612891

> The species does occur on waarnemingen.be and is considered a species `Procambarus virginalis` : https://waarnemingen.be/species/561245/
> 
> For some reason, it didn't make it to the waarnemingen.be checklist however. Maybe because the rank changed from a form (not included in the checklist) to a species _after_ the initial checklist was published. The only Procambarus that are included in the checklist are:
> 
> - [Procambarus clarkii](https://www.gbif.org/species/206108331)
> - [Procambarus acutus](https://www.gbif.org/species/206101707)

En hier: https://github.com/inbo/alien-species-portal/issues/57#issuecomment-1798618069

> Correction, it seems to be (incorrectly) considered a `variety` in waarnemingen.be, and a child of `Procambarus fallax` (https://waarnemingen.be/species/561244/) which is also not included in the checklist.

**Comment by peterdesmet** [comment]
- [x] [Procambarus virginalis](https://waarnemingen.be/species/561245/observations/) (Marmerkreeft): wordt onterecht als `Variëteit` beschouwd onder `Procambarus fallax` en komt (daarom) niet in de checklist. Het mag als soort beschouwd worden: https://craywatch.inbo.be/soorten/procambarus-virginalis/
- [x] [Faxonius virilis](https://waarnemingen.be/species/16599/observations/) (Geknobbelde Amerikaanse rivierkreeft): staat niet in checklist, misschien zijn waarnemingen te recent?

**Comment by timadriaens** [comment]
it should be there, see https://waarnemingen.be/species/16599/ (but records are indeed rather recent)

**Comment by JuulDeWitte** [comment]
Waarnemingen van [Faxonius virilis](https://waarnemingen.be/species/16599/observations/) zijn inderdaad te recent; gebruikte dataset loopt maar t.e.m. 07-01-2024

Status wel aangepast van 'verwacht' naar 'exoot'.

**Comment by JuulDeWitte** [comment]
[Procambarus virginalis](https://waarnemingen.be/species/561245/observations/) handmatig toegevoegd aan checklist.

Gevraagde update van de taxonomie kan ik binnenkort pas aanpassen. Momenteel zijn we de taxonomieschermen aan het overplaatsen van PHP naar de nieuwe site, zolang dit niet 100% rond is zijn dergelijke wijzigingen (veiligheidshalve) onmogelijk gemaakt.
