### ISSUE TITLE
Stethorus punctilllum missing

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-natagora-checklist#3]
Reported by @timadriaens:

Hi, upon working with a file that @damianooldoni harvested from the [checklist of belgian species](https://www.gbif.org/dataset/2c38cf8a-f981-4dfb-bc9d-dd2b6fc792ed) I noticed the coccinellid _[Stethorus punctillum](https://www.gbif.org/species/1043616)_ is lacking despite it having plenty of records on www.waarnemingen.be. For some reason, these did not make it onto gbif. can anyone check what happened here @peterdesmet ?

**Comment by peterdesmet** [comment]
Possible causes:

- Not a species (not the case here)
- No records before 2022 ([not the case here](https://waarnemingen.be/species/788814/observations/?date_after=2021-01-01&date_before=2021-12-31))
- No observations for which the observers agreed to make it public (likely not the case here)
- Unvalidated taxonomy?

Should be verified when publishing the new species list in 2024.

**Comment by peterdesmet** [comment]
De soort is aanwezig in waarnemingen.be: [Stethorus punctillum](https://waarnemingen.be/species/788814/) maar komt niet voor in de checklist. Wat is de reden?

**Comment by timadriaens** [comment]
Stethorus punctillum is a native species.

**Comment by peterdesmet** [comment]
Aha, comment aangepast. Verwachten we dus als native species in de checklist.

**Comment by JuulDeWitte** [comment]
In Obervation.org wordt [Stethorus pusillus](https://waarnemingen.be/species/23408/observations/) (Herbst, 1797) gezien als synoniem van [Stethorus punctillum](https://waarnemingen.be/species/788814/observations/) (Weise, 1891). Dit terwijl beiden als afzonderlijke soorten beschouwd worden op GBIF (https://www.gbif.org/species/8459975  - https://www.gbif.org/species/1043616). Andere bronnen, zoals het [Nederlands Soortenregister](https://www.nederlandsesoorten.nl/linnaeus_ng/app/views/species/nsr_taxon.php?id=155657&cat=CTAB_NAMES), volgen wel de opdeling zoals in Obervation.org.

Dus, in orde om Stethorus punctillum aan de checklist toe te voegen, maar voor de aanwezigheidslijst dus ook de waarnemingen van Stethorus pusillus mee in beschouwing te nemen?

**Comment by JuulDeWitte** [comment]
Ik zie nu dat [Stethorus pusillus](https://waarnemingen.be/species/23408/observations/) al is opgenomen in de checklist -> vervangen door [Stethorus punctillum](https://waarnemingen.be/species/788814/observations/)?

![image](https://github.com/user-attachments/assets/bcbfd1f3-467c-4d91-9b7c-c70e7ac0e321)

![image](https://github.com/user-attachments/assets/7ca80ee0-605d-40ef-984c-42db9e2c51e2)

**Comment by peterdesmet** [comment]
Je mag de synoniemie volgen van Observation.org:

- Stethorus pusillus (Herbst, 1797): een synoniem => niet opnemen in checklist
- Stethorus punctillum (Weise, 1891): een aanvaarde soort => wel opnemen in checklist

**Comment by JuulDeWitte** [comment]
[Stethorus punctillum](https://waarnemingen.be/species/788814/observations/) werd toegevoegd.
