### ISSUE TITLE
Review exotic status of some fishes

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-natagora-checklist#4]
See https://github.com/trias-project/alien-fishes-checklist/issues/24. De volgende soorten worden door onze experten als exoot beschouwd, maar staan als inheems in waarnemingen.be. Kan dit worden aangepast:

- [ ] [Abramis sapa](https://waarnemingen.be/species/22437/)
- [ ] [Vimba vimba](https://waarnemingen.be/species/2206/)
- [ ] [Romanogobio belingi](https://waarnemingen.be/species/20522/)

**Comment by JuulDeWitte** [comment]
~~Status voor de drie soorten werd aangepast naar "ingeburgerd", conform de situatie in Nederland.
Laat echter weten indien dit beter "inburgerend" of gewoon "exoot" dient te zijn!~~

~~In de eigenlijke GBIF checklist is er geen verschil tussen die drie statussen; worden allen uiteindelijke "introduced" in de import.~~

Zie nu dat de soorten zich in NL beperken tot de Rijn en zijrivieren -> status toch gewoon op exoot bij ons

**Comment by peterdesmet** [comment]
Bedankt om de status aan te passen op waarnemingen.be. Komen niet voor in checklist, want nog geen waarnemingen. 👍
