### ISSUE TITLE
Some odd scientific names

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-natagora-checklist#7]
- [x] `Micrasema longulum `: with space at end, please remove **corrected**
- [x] `Taraxacum sect. Hamata`: not a species, please update rank (will remove record from dataset) **removed**
- [x] `Brassica carinata (derived from B. nigra x B. oleracea)`: not a species, please update rank to hybrid (will remove record from dataset) **updated to Brassica carinata**
- [x] `Alcea ficifolia (A. rosea x A. rugosa)`: idem **updated to Alcea ficifolia**
- [x] `Albugo candida s.str.`: not sure what this should be **updated to Albugo candida**
- [x] `Pholiotina arrhenii sensu lato`: not a correct scientific name **removed in favour of already present Pholiotina arrhenii**
- [x] `Cortinarius spec.`: not a species, please update rank to multispecies (will remove record from dataset) **removed**

**Comment by JuulDeWitte** [comment]
Ondertussen de nodig feedback van de betreffende admins (en taxonomen) gekregen. 

Hieronder volledigheidshalve de gemaakte aanpassingen:
- _Taraxacum sect. Hamata_: blijkbaar is hier nog discussie over de rank van (o.a.) deze sectie en de onderliggende onder- of microsoorten. In dropdown de uitleg die ik van Steven Jacobs (UA) toegestuurd kreeg.
Ik zie ook in de vorige soortenlijst dat geen enkele Paardenbloem is opgenomen, hoewel er zowel van de secties als microsoorten goedgekeurde waarnemingen beschikbaar waren destijds. Akkoord dus om deze dan ook in deze update niet op te nemen. 
Mijn inziens zeker wel te bespreken of dit in de update van 2024 wel wenselijk is?

<details>
<summary>taxonomie</summary>
<br>

_Voor zo ver ik weet is de volgorde voor de nomenclatuur een 1 – 2 – 3  regel : 1. Nieuwe Heukels 2. Nieuwe rode flora 3. POWO (Plants of the world online). Indien een soort in 1 staat, wordt die naam gebruikt (ongeacht wat 2 en 3 zeggen), staat het taxon niet in 1, dan wordt er gekeken hoe die in 2 noemt (ongeacht de naam in 3) en tenslotte wordt de naam van 3 gebruikt._

_Dit leidt soms toto een soep omdat de taxonomische insteek in Nederland en België heel anders is (maar wel al meer gelijkend sinds de nieuwste edities), doordat NL meer een “lumpende” visie aanhoudt (de “Britse” visie) en België een meer splitsende (“Continentale” visie). Ook voor genera is dit zo, behalve dat in de UK en Nederland veel vlugger wetenschappelijke genetische papers gevolgd worden, waardoor veranderingen vlugger worden doorgevoerd. Tenslotte is POWO (“Britse” visie) ook allesbehalve consistent en systematisch gereviseerd, ondanks dat het het beste, meest samenhangende systeem van het moment is._ 

 _In principe worden alle secties gegroepeerd als multispecies, MAAR: in twee (semi)-apomictische complexen (paardenbloemen en bramen) worden hier als uitzonderingen beschouwd, ook omdat dit in een deel van de hanteerbare soortconcepten niet altijd als valabele soorten worden gezien. Vandaar dat men dit ook vaak “microspecies” noemt. Deze worden in [waarnemingen.be](http://waarnemingen.be/) als ondersoorten beschouwd. Of dit correct is, dat hangt van de gehanteerde visies af. Wat je jezelf terecht kunt afvragen is waarom dit voor gelijkaardige soortconcepten wel gebeurt (Alchemilla, Crataegus, Sorbus, Hieracium, Poa pratensis agg., Oenothera, …). Maar daar ligt de verklaring voor in de flora’s. In de oudere versies van de Heukels werden beide groepen niet meegeteld als soorten.  In de meest recente versie weet ik het niet. Voor de rode flora geldt dit idem voor Taraxacum, maar voor Rubus worden ze wel geteld, maar niet in de hoofdtabel. In POWO worden ze wel geteld. In principe zou dus moeten gekeken worden of die microspecies als soorten worden geteld in de Heukels. Een bijkomend argument is dat dit ook de soortlijsten zal beïnvloeden, omdat beide complexen een paar 100 microsoorten hebben._ 
</details>

- _Brassica carinata (derived from B. nigra x B. oleracea)_ en _Alcea ficifolia (A. rosea x A. rugosa)_: beide blijkbaar wel valide soorten en dus geen hybriden. Behouden in lijst en wetenschappelijk naam aangepast.
<details>
<summary>taxonomie</summary>
<br>

_Dan over hybrides en soorten…. Dat is een moeilijke, omdat ook daar verschillende visies over bestaan. Een belangrijke nuance is het verschil tussen een hybride en een soort ontstaan uit een kruising. Ongeveer 25 (tot mss zelfs 60!)% van de plantensoorten in deze wereld zijn hybridogeen van oorsprong. Zonder in detail te treden over hoe en wat, veel soorten zijn ontstaan uit kruisingen. Quasi altijd worden deze als volledige soorten gerekend. Moeilijker zijn rechtstreekse kruisingen met soortaspect. Ook hier spelen soortconcepten en visies een rol, dus ook hier voor de eenvoudigheid: de 1 – 2 – 3 regel. Ook omdat de taxonomen dat type gevallen wel altijd hebben bekeken en afgewogen. Over de twee gevallen die gemeld worden:_

_Brassica carinata wordt overal als volwaardige soort gezien, en is onderdeel van een genetische “driehoeksverhouding”: kool (oleracea) - raapzaad (rapa) - zwarte mosterd (nigra). Koolzaad (napus (oleracea x rapa) en Sereptamosterd (rapa x nigra) zijn soorten die uit die kruisingen zijn ontstaan. Carinata is gewoon de derde soort uit het geheel. Dus in principe mag het zinnetje “derived from nigra x oleracea” dus verwijderd worden. Van dit type planten zijn er dus nog voorbeelden (bv. Diphasiastrum en Kruipganzerik). Ook even meegeven dat POWO de naam Mutarda carinata geeft. Dus als die niet in de Heukels of rode flora (ik vermoed dat die hier in staat) staat, moet de naam naar Mutarda_

_Alcea ficifolia wordt iig als soort gezien door Filip V en POWO, maar is mogelijk dus een hybride of hybirdogeen taxon. Dus tenzij de rode flora en de Heukels hier een andere mening over hebben, moet die dus als soort worden gezien. Ook even meegeven dat de hybride oorsprong NIET zeker is en ook niet bewezen in een genetisch erg jonge en onstabiele groep._
</details>

- _Albugo candida s.str._: behouden in lijst en aangepast naar Albugo candida.
- _Pholiotina arrhenii sensu lato_: verwijderd uit lijst (Pholiotina arrhenii zit er reeds met volgende [ID](https://waarnemingen.be/species/195143/) in).

Zo, ik tracht asap de andere issues ook op te lossen en je de (hopelijk) finale lijst te bezorgen.

**Comment by peterdesmet** [comment]
Alle bovenstaande zijn nu opgelost, maar ik merk de volgende issues op. Die zaten ook in de vorige export, maar toen niet opgemerkt 😅:

- [x] `Hypoxylon fuscum sensu lato`: verwijderen voor de reeds aanwezige `Hypoxylon fuscum` (https://waarnemingen.be/species/16174)?
- [x] `Psathyrella sp.`: multispecies
- [x] `Lactarius sp.`: multispecies
- [x] `Pezizella rubescens `: spatie op einde
- [x] `Scymnus impexus�`: vreemd whitespace character op einde
- [x] `Aedes caspius `: spatie op einde
- [x] `Lipsothrix errans `: spaties op einde

Betreft Taraxacum: zijn er dan geen goedgekeurde soorten?

**Comment by JuulDeWitte** [comment]
* [x]  `Hypoxylon fuscum sensu lato`: verwijderd; op site reeds gewijzigd naar verzamelsoort
* [x]   `Psathyrella sp.`: verwijderd; op site reeds gewijzigd naar verzamelsoort
* [ ]  `Lactarius sp.`: verwijderd; taxonomie op site nog te wijzigen!
 * [x]  `Pezizella rubescens `: spatie in checklist en op site verwijderd
* [x]  `Scymnus impexus�`: de enige waarneming waar deze op gebaseerd was (d.d. 2023-05-20), werd ondertussen verwijderd. Records dus ook uit checklist verwijderd; whitespace character op site verwijderd
 * [x]  `Aedes caspius `: spatie in checklist en op site verwijderd. (taxonomisch is deze een beetje wazig: bij ons ondertussen op synoniem, met Ochlerotatus caspius als geaccepteerde soort - op GBIF is de situatie (nog) omgekeerd)
 * [x]  `Lipsothrix errans `: spatie in checklist en op site verwijderd

**Comment by JuulDeWitte** [comment]
M.b.t. goedgekeurde waarnemingen van Taraxacum: er zijn wel degelijk goedgekeurde waarnemingen. Dit van zowel [Taraxacum officinale s.l. (incl. all sect.)](https://waarnemingen.be/species/7539/), van secties van Paardenbloemen (bv. [Schraallandpaardenbloem](https://waarnemingen.be/species/2766/observations/)) als van de 'microsoorten' (bv. [Haakpaardenbloem](https://waarnemingen.be/species/127571/observations/))

Ik vermoed echter dat er vanwege de taxonomische onduidelijkheid die er bij deze soorten is, dat er in de eerste versie van de checklist bewust gekozen is deze soorten niet op te nemen. De hierboven genoemde soorten hadden immers destijds ook al gevalideerde waarnemingen.

Daarom ook mijn eerdere voorstel om voor de volgende update te bekijken in welke vorm we deze soorten in de checklist willen opnemen. Kunnen jullie je daar in vinden?

**Comment by peterdesmet** [comment]
Akkoord, voor Taraxacum zou ik de huidige checklist (die enkel soorten bevat) dan ook enkel de Taraxacum **soorten** opnemen, dus:

- [Taraxacum officinale s.l. (incl. all sect.)](https://waarnemingen.be/species/7539/) = soort => opnemen
- [Schraallandpaardenbloem](https://waarnemingen.be/species/2766/observations/): verkeerdelijk aangeduid als soort ipv sectie => niet opnemen
- [Haakpaardenbloem](https://waarnemingen.be/species/127571/observations/): aangeduid als ondersoort => niet opnemen
- Taraxacum sect. Hamata: een sectie => niet opnemen

**Comment by JuulDeWitte** [comment]
[Taraxacum officinale s.l. (incl. all sect.)](https://waarnemingen.be/species/7539/) werd toegevoegd.
