### ISSUE TITLE
Waar zijn Bacteria, Chromista, Protozoa?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/natuurpunt-natagora-checklist#9]
@JuulDeWitte In de nieuwe publicatie ontbreken:

```
Bacteria	Nostoc commune
Bacteria	Nostoc pruniforme
Chromista	Ascophyllum nodosum
Chromista	Attheya armata
Chromista	Bacillaria paxillifer
Chromista	Chorda filum
Chromista	Cymatopleura solea
Chromista	Cystoseira baccata
Chromista	Diploneis didyma
Chromista	Fucus serratus
Chromista	Fucus spiralis
Chromista	Fucus vesiculosus
Chromista	Halidrys siliquosa
Chromista	Himanthalia elongata
Chromista	Laminaria digitata
Chromista	Laminaria hyperborea
Chromista	Melosira moniliformis
Chromista	Nassula ornata
Chromista	Noctiluca scintillans
Chromista	Petalonia fascia
Chromista	Phaeocystis pouchetii
Chromista	Saccharina latissima
Chromista	Sargassum muticum
Chromista	Undaria pinnatifida
Protozoa	Euglena mutabilis
Protozoa	Phacus longicauda
```

Kunnen die er in de volgende update weer aan toegevoegd worden?

**Comment by JuulDeWitte** [comment]
Vreemd, in de oorspronkelijk uitgestuurde adminlijst zijn deze wel opgenomen. Lijkt ook alsof er bij de meeste soorten geen wijzigingen waren t.o.v. de eerste versie van de checklist. ~~Snap dus niet goed waarom de latere queries deze niet mee hebben opgepikt.~~

![image](https://github.com/user-attachments/assets/cff20eeb-be01-43d1-aac4-4e23f2926b63)

**Comment by JuulDeWitte** [comment]
Ik zie nu dat de soorten wel degelijk zijn opgenomen in de soortenlijst. 
Zie bijvoorbeeld (Nostoc):

![image](https://github.com/user-attachments/assets/8c0db209-80da-4176-90d9-79217cf7cf59)
en 
![image](https://github.com/user-attachments/assets/105531a3-cef6-4991-bc40-868dcf0548b8)

Is er hier mogelijk een vergissing gebeurd?

**Comment by peterdesmet** [comment]
Je hebt gelijk, ze staan er allemaal effectief in (behalve `Cystoseira baccata` en `Phaeocystis pouchetii`). Maar ze hebben alle `Animalia` als kingdom, wat fout is. Is dat op te lossen in de query?

**Comment by JuulDeWitte** [comment]
In deze fase is het denk ik sneller/veiliger om dit handmatig aan te passen. Ik zet me er nog even aan.

**Comment by JuulDeWitte** [comment]
Aangepast voor de opgelijste soorten.

**Comment by peterdesmet** [comment]
Bedankt, ik heb ook nog `Saccharina latissima` aangepast naar Chromista.
